# Configurações para aplicação Single Page Application
[build]
  command = "npm run build"
  publish = "dist"

# Configuração para SPA - redireciona todas as rotas para o index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 