services:
  - type: web
    name: jogo
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: FRONTEND_URL_PROD
        value: https://arterapida.netlify.app
      - key: MAX_PLAYERS_PER_ROOM
        value: 10
      - key: LOG_LEVEL
        value: info 